---
title: "Markdown"
output: html_document
date: "2023-11-28"
---

```{r setup, include=FALSE}
library(readr)
DOHMH_HIV_AIDS_Annual_Report <- read_csv("data/DOHMH_HIV_AIDS_Annual_Report.csv")
View(DOHMH_HIV_AIDS_Annual_Report)

# Install renv:
if (!is.element("renv", installed.packages()[, 1])) {
  install.packages("renv", dependencies = TRUE)
}
require("renv")

if (!is.element("languageserver", installed.packages()[, 1])) {
  install.packages("languageserver", dependencies = TRUE)
}
require("languageserver")

DOHMH_HIV_AIDS_Annual_Report <- read.csv("data/DOHMH_HIV_AIDS_Annual_Report.csv", header = FALSE,
                         stringsAsFactors = TRUE)

# The following code (optional) can be used to name the attributes in the
# iris_dataset:

# names(iris_dataset) <- c("sepal length in cm", "sepal width in cm",
#                          "petal length in cm", "petal width in cm", "class")

if (!is.element("readr", installed.packages()[, 1])) {
  install.packages("readr", dependencies = TRUE)
}

## STEP 4. Load sample datasets that are provided as part of a package ----
if (!is.element("mlbench", installed.packages()[, 1])) {
  install.packages("mlbench", dependencies = TRUE)
}
require("mlbench")
```



```{r cars}
## STEP 4. Load sample datasets that are provided as part of a package ----
if (!is.element("mlbench", installed.packages()[, 1])) {
  install.packages("mlbench", dependencies = TRUE)
}
require("mlbench")

data("DOHMH_HIV_AIDS_Annual_Report")
##Step 5

dim(DOHMH_HIV_AIDS_Annual_Report)

## Step 6
sapply(DOHMH_HIV_AIDS_Annual_Report, class)
## Step 7 Measure of Central Tendancy

DOHMH_HIV_AIDS_Annual_Report_freq <- DOHMH_HIV_AIDS_Annual_Report$`Death rate`
cbind(frequency = table(DOHMH_HIV_AIDS_Annual_Report_freq),
      percentage = prop.table(table(DOHMH_HIV_AIDS_Annual_Report_freq)) * 100)


```



```{r pressure, echo=FALSE}
if (!is.element("e1071", installed.packages()[, 1])) {
  install.packages("e1071", dependencies = TRUE)
}
require("e1071")

sapply(DOHMH_HIV_AIDS_Annual_Report[, c(1,7, 9, 11, 14,15, 17)],  kurtosis, type = 2)

### STEP 13. Measure the skewness of each variable ----


```


